name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses Linux server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Streamlit App
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          streamlit run streamlit_app.py
